# themes from https://github.com/alacritty/alacritty-theme

# import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
[mouse]
hide_when_typing = true

[font]
size = 12

[font.normal]
family = "Hack Nerd Font"

[window]
decorations = "none"

# "OnlyLeft" | "OnlyRight" | "Both" | "None" # (macos only)
# option_as_alt = "Both"

[window.padding]
x = 7
y = 0

[keyboard]
bindings = [
  # https://github.com/alacritty/alacritty/issues/34
  { mods = "Control", key = "F", action = "ToggleFullscreen" },
  { mods = "Control", key = "N", action = "CreateNewWindow" },
  # { mods = "Control", key = "6", chars = "\u005E" },
]
